version: 2.1
commands:
  deploy:
    description: "Deployment of rules server"
    parameters:
      hostname:
        type: string
        default: "ssh.staging.openchs.org"
    steps:
      - attach_workspace:
          at: ~/artifacts

      - run:
          name: Install dependencies and deploy to server
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install make openssl python3-pip
            sudo apt-get install unzip
            sudo pip3 install awscli --upgrade

      - run:
          name: Copy artifacts to server
          command: |
            scp -o StrictHostKeyChecking=no ~/artifacts/rules-server.zip ec2-user@<< parameters.hostname >>:/tmp

      - run:
          name: Deploy server
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@<< parameters.hostname >> \<< EOF
            sudo rm -rf /opt/rules-server
            sudo unzip -qq /tmp/rules-server.zip -d /opt/
            cd /opt/rules-server
            sudo chmod a+x /opt/rules-server/deploy/install.sh
            sudo /opt/rules-server/deploy/install.sh $OPENCHS_UPLOAD_USER_USER_NAME $OPENCHS_UPLOAD_USER_PASSWORD $AVNI_TZ
            EOF

jobs:
  app_test:
    docker:
      - image: cimg/node:10.15.1

    working_directory: ~/rules-server

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: NPM Install
          no_output_timeout: 30m
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm test

  app_build:
    docker:
      - image: cimg/node:10.15.1

    working_directory: ~/rules-server

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: NPM Install
          no_output_timeout: 30m
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: zip -r ~/rules-server.zip ../rules-server

      - run: tar -czvf ~/rules-server.tgz  -C ../rules-server .

      - run: mkdir -p ~/artifacts

      - run: echo $CIRCLE_BUILD_NUM > ~/artifacts/build_version

      - run: cp ~/rules-server.zip ~/artifacts/

      - run: cp ~/rules-server.tgz ~/artifacts/

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - build_version
            - rules-server.zip
            - rules-server.tgz

      - store_artifacts:
          path: ~/artifacts

  STAGING_deploy:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.staging.openchs.org"
  PRERELEASE_deploy:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.prerelease.openchs.org"
  PERF_deploy:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.perf.openchs.org"
  PRODUCTION_deploy:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.server.openchs.org"

workflows:
  version: 2
  test_and_build:
    jobs:
      - app_test
      - app_build:
          requires:
            - app_test
      - STAGING_deploy:
          context: non-prod-deploy
          filters:
            branches:
              only:
                - master
                - /^3\..*/
          requires:
            - app_build
      - PRODUCTION_approve:
          type: approval
          requires:
            - app_build
      - PRODUCTION_deploy:
          context: prod-deploy
          requires:
            - PRODUCTION_approve
      - PRERELEASE_approve:
          type: approval
          requires:
            - app_build
      - PRERELEASE_deploy:
          context: non-prod-deploy
          requires:
            - PRERELEASE_approve
      - PERF_approve:
          type: approval
          requires:
            - app_build
      - PERF_deploy:
          context: non-prod-deploy
          requires:
            - PERF_approve
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/0fdffde721194986f2a0
